name = "danmu-api"
main = "cf_worker.js"
compatibility_date = "2024-09-21"


# 环境变量
[vars]
ENABLE_ASYMMETRIC_AUTH_ENV = "false"
USER_AGENT_LIMITS_CONFIG = '''{
    "MisakaDanmaku":{
        "enabled":true,
        "name":"misaka-dd-danmaku",
        "version":"1.0.0",
        "pattern":"misaka-dd-danmaku",
        "maxRequestsPerHour":100,
        "maxRequestsPerDay":1000,
        "description":"Misaka弹幕专用客户端"
        }    

}'''

# KV 绑定
[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "3f2e505906b04bbf85d47b9194706d1d"

